name: pytest

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
      uv-version:
        required: false
        type: string
        default: latest
      debug-enabled:
        required: false
        type: boolean
        default: false

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug-enabled }}
        with:
          detached: true
      # We support a specific Python version as arg or reading it from
      # the .python-version file
      - name: Install uv and Python
        if: ${{ inputs.python-version != '' }}
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv-version }}
          enable-cache: true
          cache-dependency-glob: uv.lock
          python-version: ${{ inputs.python-version }}
      - name: Install uv and Python using .python-version
        if: ${{ inputs.python-version == '' }}
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv-version }}
          enable-cache: true
          cache-dependency-glob: uv.lock
      # Alternative, sometimes faster due to Github caching the Python version
      # - name: "Set up Python"
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version-file: ".python-version" OR python-version: ${{ inputs.python-version }}
      - name: Install the project
        run: |
          uv sync --locked --dev
      - name: Test with pytest
        run: |
          uv run pytest
